#!/usr/bin/env python

import json
import unittest
import requests
import os
if os.name == 'nt':
    class timeout_decorator:
        @staticmethod
        def timeout(*args, **kwargs):
            return lambda f: f # return a no-op decorator
else:
    import timeout_decorator
from em_test_utils import *


#  This file was automatically generated by EvoMaster on 2025-10-01T06:32:36.301628323Z[GMT]
#  
#  The generated test suite contains 13 tests
#  
#  Covered targets: 72
#  
#  Used time: 0h 2m 6s
#  
#  Needed budget for current results: 90%
#  
#  This file contains test cases that represent successful calls.
class EvoMaster_successes_Test(unittest.TestCase):

    
    baseUrlOfSut = "http://localhost:8080"
    
    
    
    
    
    
    
    
    
    
    # Calls:
    # (200) POST:/wrk2-api/user/register
    @timeout_decorator.timeout(60)
    def test_0(self):
        
        headers = {}
        headers["content-type"] = "application/x-www-form-urlencoded"
        body = "req_id=137&first_name=JJcTQO&last_name=58icDR&username=j1&password=e3GG_eKLD9M&user_id=444"
        headers['Accept'] = "application/octet-stream"
        res_0 = requests \
                .post(self.baseUrlOfSut + "/wrk2-api/user/register",
                    headers=headers, data=body)
        
        assert res_0.status_code == 200
        assert "application/octet-stream" in res_0.headers["content-type"]
    
    
    # Calls:
    # (200) POST:/wrk2-api/user/unfollow
    @timeout_decorator.timeout(60)
    def test_1(self):
        
        headers = {}
        headers["content-type"] = "application/x-www-form-urlencoded"
        body = "req_id=704&user_id=95&followee_id=941"
        headers['Accept'] = "application/octet-stream"
        res_0 = requests \
                .post(self.baseUrlOfSut + "/wrk2-api/user/unfollow",
                    headers=headers, data=body)
        
        assert res_0.status_code == 200
        assert "application/octet-stream" in res_0.headers["content-type"]
    
    
    # Calls:
    # (200) POST:/wrk2-api/user/follow
    @timeout_decorator.timeout(60)
    def test_2(self):
        
        headers = {}
        headers["content-type"] = "application/x-www-form-urlencoded"
        body = "req_id=492&user_id=385&followee_id=703"
        headers['Accept'] = "application/octet-stream"
        res_0 = requests \
                .post(self.baseUrlOfSut + "/wrk2-api/user/follow",
                    headers=headers, data=body)
        
        assert res_0.status_code == 200
        assert "application/octet-stream" in res_0.headers["content-type"]
    
    
    # Calls:
    # (200) POST:/wrk2-api/post/compose
    @timeout_decorator.timeout(60)
    def test_3(self):
        
        headers = {}
        headers["content-type"] = "application/x-www-form-urlencoded"
        body = "req_id=756&username=6T1&user_id=466&text=evx_cO9Jd0WHXFJQ&media_ids=&media_types=&post_type=9"
        headers['Accept'] = "application/octet-stream"
        res_0 = requests \
                .post(self.baseUrlOfSut + "/wrk2-api/post/compose",
                    headers=headers, data=body)
        
        assert res_0.status_code == 200
        assert "application/octet-stream" in res_0.headers["content-type"]
    
    
    # Calls:
    # (200) GET:/wrk2-api/user-timeline/read
    @timeout_decorator.timeout(60)
    def test_4(self):
        
        headers = {}
        headers['Accept'] = "application/json"
        res_0 = requests \
                .get(self.baseUrlOfSut + "/wrk2-api/user-timeline/read?" + 
                    "req_id=93&" + 
                    "user_id=437&" + 
                    "start=234&" + 
                    "stop=973",
                    headers=headers)
        
        assert res_0.status_code == 200
        assert "application/json" in res_0.headers["content-type"]
        assert len(res_0.json()) == 0
    
    
    # Calls:
    # (200) GET:/wrk2-api/home-timeline/read
    @timeout_decorator.timeout(60)
    def test_5(self):
        
        headers = {}
        headers['Accept'] = "application/json"
        res_0 = requests \
                .get(self.baseUrlOfSut + "/wrk2-api/home-timeline/read?" + 
                    "req_id=244&" + 
                    "user_id=669&" + 
                    "start=197&" + 
                    "stop=53",
                    headers=headers)
        
        assert res_0.status_code == 200
        assert "application/json" in res_0.headers["content-type"]
        assert len(res_0.json()) == 0
    
    
    # Calls:
    # (200) GET:/wrk2-api/home-timeline/read
    @timeout_decorator.timeout(60)
    def test_6(self):
        
        headers = {}
        headers['Accept'] = "application/json"
        res_0 = requests \
                .get(self.baseUrlOfSut + "/wrk2-api/home-timeline/read?" + 
                    "req_id=-1728769186&" + 
                    "user_id=963&" + 
                    "start=131&" + 
                    "stop=457",
                    headers=headers)
        
        assert res_0.status_code == 200
        assert "application/json" in res_0.headers["content-type"]
        assert len(res_0.json()) == 0
    
    
    # Calls:
    # (200) GET:/wrk2-api/home-timeline/read
    @timeout_decorator.timeout(60)
    def test_7(self):
        
        headers = {}
        headers['Accept'] = "application/json"
        res_0 = requests \
                .get(self.baseUrlOfSut + "/wrk2-api/home-timeline/read?" + 
                    "req_id=569&" + 
                    "user_id=-1751256861&" + 
                    "start=873&" + 
                    "stop=355",
                    headers=headers)
        
        assert res_0.status_code == 200
        assert "application/json" in res_0.headers["content-type"]
        assert len(res_0.json()) == 0
    
    
    # Calls:
    # (200) GET:/wrk2-api/home-timeline/read
    @timeout_decorator.timeout(60)
    def test_8(self):
        
        headers = {}
        headers['Accept'] = "application/json"
        res_0 = requests \
                .get(self.baseUrlOfSut + "/wrk2-api/home-timeline/read?" + 
                    "req_id=101&" + 
                    "user_id=98&" + 
                    "start=1022878777&" + 
                    "stop=-26090129",
                    headers=headers)
        
        assert res_0.status_code == 200
        assert "application/json" in res_0.headers["content-type"]
        assert len(res_0.json()) == 0
    
    
    # Calls:
    # (200) GET:/wrk2-api/home-timeline/read
    @timeout_decorator.timeout(60)
    def test_9(self):
        
        headers = {}
        headers['Accept'] = "application/json"
        res_0 = requests \
                .get(self.baseUrlOfSut + "/wrk2-api/home-timeline/read?" + 
                    "req_id=56&" + 
                    "user_id=762&" + 
                    "start=-1577300699&" + 
                    "stop=128",
                    headers=headers)
        
        assert res_0.status_code == 200
        assert "application/json" in res_0.headers["content-type"]
        assert len(res_0.json()) == 0
    
    
    # Calls:
    # (200) GET:/wrk2-api/user-timeline/read
    @timeout_decorator.timeout(60)
    def test_10(self):
        
        headers = {}
        headers['Accept'] = "application/json"
        res_0 = requests \
                .get(self.baseUrlOfSut + "/wrk2-api/user-timeline/read?" + 
                    "req_id=145&" + 
                    "user_id=31&" + 
                    "start=-930050225&" + 
                    "stop=232",
                    headers=headers)
        
        assert res_0.status_code == 200
        assert "application/json" in res_0.headers["content-type"]
        assert len(res_0.json()) == 0
    
    
    # Calls:
    # (200) GET:/wrk2-api/user-timeline/read
    @timeout_decorator.timeout(60)
    def test_11(self):
        
        headers = {}
        headers['Accept'] = "application/json"
        res_0 = requests \
                .get(self.baseUrlOfSut + "/wrk2-api/user-timeline/read?" + 
                    "req_id=982&" + 
                    "user_id=849&" + 
                    "start=497&" + 
                    "stop=-38443418",
                    headers=headers)
        
        assert res_0.status_code == 200
        assert "application/json" in res_0.headers["content-type"]
        assert len(res_0.json()) == 0
    
    
    # Calls:
    # (200) GET:/wrk2-api/user-timeline/read
    @timeout_decorator.timeout(60)
    def test_12(self):
        
        headers = {}
        headers['Accept'] = "application/json"
        res_0 = requests \
                .get(self.baseUrlOfSut + "/wrk2-api/user-timeline/read?" + 
                    "req_id=-1247724426&" + 
                    "user_id=865&" + 
                    "start=212&" + 
                    "stop=844",
                    headers=headers)
        
        assert res_0.status_code == 200
        assert "application/json" in res_0.headers["content-type"]
        assert len(res_0.json()) == 0


if __name__ == '__main__':
    unittest.main()
